spring:
  application:
    name: configuration-server
  cloud:
    compatibility-verifier:
      enabled: false
    config:
      server:
        native:
          search-locations: configuration-server/src/main/resources/config
  profiles:
    active: native

server:
  port: 8888




