spring:
  application:
    name: configuration-server

  cloud:
    config:
      server:
        git:
          uri: https://github.com/SahanDhanujaya/Smart-Parking-Management-System.git
server:
  port: 8888
