spring:
  application:
    name: user-service

  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration



  cloud:
    compatibility-verifier:
      enabled: false
  config:
    import: optional:configserver:http://localhost:8888
  jackson:
    serialization:
      fail-on-empty-beans: false