spring:
  datasource:
    url: jdbc:mysql://localhost:3306/vehicle_db
    username: root
    password: 95334238Sd$
    driver-class-name: com.mysql.cj.jdbc.Driver

custom:
  message: hello from config server

